export const FETCHING_COIN_DATA = "FETCHING_COIN_DATA";
export const FETCHING_COIN_DATA_SUCCESS = "FETCHING_COIN_DATA_SUCCESS";
export const FETCHING_COIN_DATA_FAILURE = "FETCHING_COIN_DATA_FAILURE";
export const ADD_TICKER = "ADD_TICKER";
export const REMOVE_TICKER = "REMOVE_TICKER";